### PR TITLE
[FBZ-10499] Migrate eydr Recipe to v7

### PR DESCRIPTION
**Pull request by kvbautista**
Description of your patch
-------------
Added eydr recipe support for v7 stack using PostgreSQL versions 10, 11, 12, 13 and 14

Recommended Release Notes
-------------
Added eydr recipe support for v7 stack using PostgreSQL versions 10, 11, 12, 13 and 14

Estimated risk
-------------
High

Components involved
-------------
Clients using eydr recipe

Dependencies
-------------
Environments that use either MySQL or PostgreSQL as database

Description of testing done
-------------
- Create 2 v7 environments (with the other on a different region) using any of the PostgreSQL version listed below:
  - 10 (via UI)
  - 11 (via UI)
  - 12 (via Environment Variables and using changes from PR145)
  - 13 (via Environment Variables and using changes from PR145)
  - 14 (via Environment Variables and using changes from PR145)
- Follow the `README.md` file instructions to setup the pre-requisites
- Upload `eydr` custom recipe with the modified details for Master env and Slave env
- Test if replication or failover will work via modifying `eydr/attributues/replication.rb`
- For replication:
  - Once set to `true`, the Slave environment should be streaming replication (can be verified via `select * from pg_stat_wal_receiver;`)
  - Also can be verified from Master env via `select * from pg_stat_replication;`
  - Test by adding data onto Master env and check if Slave env gets the update.

QA Instructions
-------------
- Create 2 v7 environments (with the other on a different region) using any of the PostgreSQL version listed below:
  - 10 (via UI)
  - 11 (via UI)
  - 12 (via Environment Variables and using changes from PR145)
  - 13 (via Environment Variables and using changes from PR145)
  - 14 (via Environment Variables and using changes from PR145)
- Follow the `README.md` file instructions to setup the pre-requisites
- Upload `eydr` custom recipe with the modified details for Master env and Slave env
- Test if replication or failover will work via modifying `eydr/attributues/replication.rb`
- For replication:
  - Once set to `true`, the Slave environment should be streaming replication (can be verified via `select * from pg_stat_wal_receiver;`)
  - Also can be verified from Master env via `select * from pg_stat_replication;`
  - Test by adding data onto Master env and check if Slave env gets the update.

### CODE REVIEW

**Comment by mushyy** [comment]
Fails linting process, please run it through cookstyle and make the appropriate changes.

**Review by mushyy — CHANGES_REQUESTED** [review]
^

**Comment by dvalfre** [comment]
@kdotbautista besides what was mentioned above, do add a Readme file at the `custom-cookbooks/eydr` level in the same way that other recipes already have.

**Comment by kvbautista** [comment]
Fixed linter findings and added `README` file under `custom-cookbooks/eydr`

**Comment by rupikakapoor** [comment]
@kdotbautista : it is still falling linting:

```
Offenses:

custom-cookbooks/eydr/cookbooks/eydr/attributes/replication.rb:23:9: C: [Correctable] Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping. (https://rubystyle.guide#consistent-string-literals)
default['failover'] = false
        ^^^^^^^^^^
custom-cookbooks/eydr/cookbooks/eydr/recipes/postgres_replication.rb:6:1: W: Lint/UselessAssignment: Useless assignment to variable - postgres_version. (https://rubystyle.guide#underscore-unused-vars)
postgres_version = node["postgresql"]["short_version"]
^^^^^^^^^^^^^^^^
custom-cookbooks/eydr/cookbooks/eydr/recipes/postgres_replication.rb:14:10: C: [Correctable] Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping. (https://rubystyle.guide#consistent-string-literals)
    user 'postgres'
         ^^^^^^^^^^
custom-cookbooks/eydr/cookbooks/eydr/recipes/postgres_replication.rb:23:10: C: [Correctable] Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping. (https://rubystyle.guide#consistent-string-literals)
    user 'postgres'
         ^^^^^^^^^^

19 files inspected, 4 offenses detected, 3 offenses auto-correctable
```

**Review by rupikakapoor — APPROVED** [review]
LGTM

**Pull request merged**
