### PR TITLE
FBZ-10543 Remove TLS 1.0 and 1.1 from default configuration.

### PR DESCRIPTION
**Pull request by rupikakapoor**
### Description of your patch
Removed default support for TLS 1.0 and 1.0. 

### Recommended Release Notes
Removed default support for TLS 1.0 and 1.0, now TLS 1.0 and TLS 1.1 can be enabled using Environment Variables. 

### Estimated risk
High

### Components involved
All clients with SSL enabled for environmnet. 

### Dependencies
ey-app

### Description of testing done
**Case1:**

* Create v7 environment 
* Add environmnet variable `EY_TLS10_ENABLED` as `true` and boot environmnet and enable SSL for environmnet.
* Verify file `/etc/nginx/servers/<app>/default.ssl_cipher` for enabled TLS versions. 

**Case2:**

* Create v7 environment 
* Add environmnet variable `EY_TLS11_ENABLED` as `true` and boot environmnet and enable SSL for environmnet.
* Verify file `/etc/nginx/servers/<app>/default.ssl_cipher` for enabled TLS versions.

### CODE REVIEW

**Comment by dvalfre** [comment]
@rupikakapoor seems the description of the patch, the recommended release notes, and the dependencies come from a different PR...

**Comment by rupikakapoor** [comment]
> @rupikakapoor seems the description of the patch, the recommended release notes, and the dependencies come from a different PR...

updated description now.

**Review by mushyy — COMMENTED** [review]
Why are we settings TLS1.0 and TLS1.1 if just TLS1.0 is enabled?; We should also, probably ship TLS1.3 as our nginx version should support it

**Review by dvalfre — APPROVED** [review]
This looks good to me.

**Pull request merged**
